import {
  OsintSource,
  OsintResult,
  OsintDiscovery,
  OsintEntity,
  OsintEntityResolutionMatch,
  OsintGraphNode,
  OsintGraphEdge,
  OsintTimelineEvent,
  OsintCollectorJob,
  OsintSearchRecord,
} from "./osint-types";

// Catálogo Real de Conectores OSINT
export const OSINT_SOURCES_CATALOG: OsintSource[] = [
  {
    id: "src-search",
    name: "SearchConnector (Motores Abertos)",
    type: "SearchConnector",
    category: "WEB",
    status: "ONLINE",
    description: "Indexação passiva em índices públicos abertos e motores de busca sem interação direta com o alvo.",
    reliabilityScore: 0.88,
    rateLimit: "60 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-domain",
    name: "DomainConnector (WHOIS / RDAP)",
    type: "DomainConnector",
    category: "DOMINIOS",
    status: "ONLINE",
    description: "Consulta aos registos oficiais ICANN/IANA RDAP e entidades registradoras de TLDs públicos.",
    reliabilityScore: 0.95,
    rateLimit: "30 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-dns",
    name: "DNSConnector (Resolução Global)",
    type: "DNSConnector",
    category: "DNS",
    status: "ONLINE",
    description: "Consulta e verificação de registos A, AAAA, MX, NS, SOA e TXT em servidores raiz autoritativos.",
    reliabilityScore: 0.99,
    rateLimit: "120 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-crt",
    name: "CertificateConnector (CT Logs crt.sh)",
    type: "CertificateConnector",
    category: "CERTIFICADOS",
    status: "ONLINE",
    description: "Auditoria contínua de Certificate Transparency logs públicos (RFC 6962) para deteção de SANs.",
    reliabilityScore: 0.99,
    rateLimit: "45 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-docs",
    name: "PublicDocumentConnector (Boletins & Editais)",
    type: "PublicDocumentConnector",
    category: "DOCUMENTOS",
    status: "ONLINE",
    description: "Ingestão e parsing textual de Diários da República, editais judiciais e registos mercantis públicos.",
    reliabilityScore: 0.94,
    rateLimit: "20 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-news",
    name: "PublicNewsConnector (Agências de Notícias)",
    type: "PublicNewsConnector",
    category: "NOTICIAS",
    status: "ONLINE",
    description: "Monitorização de fontes abertas de imprensa institucional, boletins regulatórios e agências.",
    reliabilityScore: 0.85,
    rateLimit: "40 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-social",
    name: "SocialPublicConnector (Perfis Passivos)",
    type: "SocialPublicConnector",
    category: "SOCIAL",
    status: "NAO_CONFIGURADA",
    description: "Requer chaves de API oficiais das plataformas ou credenciais corporativas de ingestão passiva.",
    reliabilityScore: 0.75,
    rateLimit: "Indisponível",
    requiresApiKey: true,
  },
  {
    id: "src-image",
    name: "ImageConnector (EXIF / Perceptual Hash)",
    type: "ImageConnector",
    category: "IMAGEM",
    status: "ONLINE",
    description: "Extração de metadados EXIF, assinatura SHA-256 e cálculo de similaridade por perceptual hashing.",
    reliabilityScore: 0.92,
    rateLimit: "15 req/min",
    requiresApiKey: false,
  },
  {
    id: "src-custom",
    name: "CustomConnector (Webhook do Tenant)",
    type: "CustomConnector",
    category: "WEB",
    status: "NAO_CONFIGURADA",
    description: "Conector personalizado para bases de dados proprietárias ou feeds internos da organização.",
    reliabilityScore: 0.0,
    rateLimit: "Não definido",
    requiresApiKey: true,
  },
];

// Pesquisas Recentes
export const INITIAL_SEARCH_RECORDS: OsintSearchRecord[] = [
  {
    id: "osint-srch-001",
    targetQuery: "shadow-secure-transfer.net",
    targetType: "DOMINIO",
    contextNotes: "Verificação de infraestrutura de domínio, servidores de nomes e certificados TLS associados ao C2.",
    investigationRef: "CASO-2026-001 (Operação Sombra Digital)",
    status: "CONCLUIDA",
    resultsCount: 8,
    discoveriesCount: 3,
    createdAt: "2026-10-02 18:40 UTC+1",
    requestedBy: "Capitão Silva (Perito Digital)",
  },
  {
    id: "osint-srch-002",
    targetQuery: "Dr. Manuel V. (NIF 5410982319)",
    targetType: "PESSOA",
    contextNotes: "Levantamento passivo de vínculos públicos societários, menções em diários oficiais e endereços empresariais.",
    investigationRef: "CASO-2026-001 (Operação Sombra Digital)",
    status: "EM_ANALISE",
    resultsCount: 5,
    discoveriesCount: 2,
    createdAt: "2026-10-03 09:15 UTC+1",
    requestedBy: "Tenente Manuel (Eng. Forense)",
  },
  {
    id: "osint-srch-003",
    targetQuery: "Vortex Consulting Offshore Ltd.",
    targetType: "EMPRESA",
    contextNotes: "Rastreio em registos públicos internacionais de empresas e estruturas de trust.",
    investigationRef: "CASO-2026-001 (Operação Sombra Digital)",
    status: "EM_ANALISE",
    resultsCount: 6,
    discoveriesCount: 1,
    createdAt: "2026-10-03 11:20 UTC+1",
    requestedBy: "Capitão Silva (Perito Digital)",
  },
];

// Resultados Normalizados (Fonte ≠ Evidência ≠ Descoberta)
export const INITIAL_OSINT_RESULTS: OsintResult[] = [
  {
    id: "res-001",
    searchId: "osint-srch-001",
    source: "DNSConnector (Resolução Autoritativa)",
    sourceType: "DNSConnector",
    category: "DOMINIOS",
    url: "dns://shadow-secure-transfer.net",
    title: "Registos DNS Activos: A (185.220.101.45) & MX (mail.shadow-secure-transfer.net)",
    snippet: "A: 185.220.101.45 (TTL 300) | NS: ns1.privacy-dns.is, ns2.privacy-dns.is | MX: mail.shadow-secure-transfer.net (Prio 10)",
    publishedAt: "2026-09-27 10:00:00Z",
    collectedAt: "2026-10-02 18:41:10 UTC+1",
    contentHash: "4f9b8c12a3d4e5f67890123456789abcdef0123456789abcdef0123456789abc",
    entities: ["shadow-secure-transfer.net", "185.220.101.45", "privacy-dns.is"],
    indicators: ["Nó de saída Tor (AS9009)", "Serviço de privacidade Whois ativado"],
    isPreservedAsEvidence: true,
    evidenceId: "ev-001",
  },
  {
    id: "res-002",
    searchId: "osint-srch-001",
    source: "CertificateConnector (Certificate Transparency crt.sh)",
    sourceType: "CertificateConnector",
    category: "CERTIFICADOS",
    url: "https://crt.sh/?q=shadow-secure-transfer.net",
    title: "Certificado TLS Emitido por Let's Encrypt Authority X3",
    snippet: "Serial: 04:a9:81:22:ff | Validade: 2026-08-15 a 2026-11-13 | SANs: shadow-secure-transfer.net, api.shadow-secure-transfer.net, vault.shadow-secure-transfer.net",
    publishedAt: "2026-08-15 14:22:00Z",
    collectedAt: "2026-10-02 18:41:25 UTC+1",
    contentHash: "8e7d6c5b4a3210fedcba9876543210fedcba9876543210fedcba9876543210fe",
    entities: ["shadow-secure-transfer.net", "api.shadow-secure-transfer.net"],
    indicators: ["Subdomínio api e vault observados em logs públicos"],
    isPreservedAsEvidence: true,
    evidenceId: "ev-002",
  },
  {
    id: "res-003",
    searchId: "osint-srch-002",
    source: "PublicDocumentConnector (Boletim Oficial de Angola)",
    sourceType: "PublicDocumentConnector",
    category: "DOCUMENTOS",
    url: "https://governo.gov.ao/diario-oficial/publicacoes/2024/03/edital-sociedades-12.pdf",
    title: "Registo Mercantil: Constituições Societárias de Luanda (Edital 12/2024)",
    snippet: "Designação: Dr. Manuel V. como procurador signatário com plenos poderes de movimentação fiduciária associado ao NIF 5410982319.",
    publishedAt: "2024-03-12 00:00:00Z",
    collectedAt: "2026-10-03 09:16:04 UTC+1",
    contentHash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
    entities: ["Dr. Manuel V.", "NIF 5410982319", "Luanda / Talatona"],
    indicators: ["Identificador fiscal NIF correspondente", "Poderes fiduciários em ata pública"],
    isPreservedAsEvidence: true,
  },
  {
    id: "res-004",
    searchId: "osint-srch-003",
    source: "DomainConnector (RDAP / Registador Público Internacional)",
    sourceType: "DomainConnector",
    category: "DOMINIOS",
    url: "https://rdap.identity-digital.services/domain/vortex-consulting.org",
    title: "Registo de Domínio vortex-consulting.org",
    snippet: "Data de Criação: 2024-03-14 | Registrant Organization: Vortex Consulting Offshore Ltd | Contacto Administrativo: +41 79 123 4567 | Localização: Genebra, Suíça",
    publishedAt: "2024-03-14 09:30:00Z",
    collectedAt: "2026-10-03 11:21:12 UTC+1",
    contentHash: "3c2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3210fedcba9876543210fedc",
    entities: ["vortex-consulting.org", "Vortex Consulting Offshore Ltd.", "+41 79 123 4567"],
    indicators: ["Contacto telefónico suíço coincidente com WhatsApp periciado"],
    isPreservedAsEvidence: true,
  },
  {
    id: "res-005",
    searchId: "osint-srch-001",
    source: "PublicNewsConnector (Agência Financeira Regulada)",
    sourceType: "PublicNewsConnector",
    category: "NOTICIAS",
    url: "https://angola-economia.ao/noticias/alerta-fraudes-pagamentos-falsos-2026",
    title: "Alerta de Ciberfraude: Domínios de Transferência Clandestina",
    snippet: "Autoridades financeiras notificam campanhas de falsos links bancários utilizando terminações genéricas internacionais (.net, .is).",
    publishedAt: "2026-09-25 15:30:00Z",
    collectedAt: "2026-10-02 18:42:00 UTC+1",
    contentHash: "6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e",
    entities: ["shadow-secure-transfer.net"],
    indicators: ["Padrão de nomenclatura listado em comunicado público"],
    isPreservedAsEvidence: false,
  }
];

// Descobertas Formais (Construídas e Validadas pelo Perito)
export const INITIAL_OSINT_DISCOVERIES: OsintDiscovery[] = [
  {
    id: "disc-001",
    searchId: "osint-srch-001",
    investigationId: "CASO-2026-001",
    title: "Coincidência de Contacto Telefónico Suíço (+41 79 123 4567) em Domínio e Extração",
    description: "O registo público RDAP do domínio vortex-consulting.org apresenta o mesmo contacto suíço identificado nas mensagens apagadas recuperadas via extração forense do dispositivo móvel apreendido.",
    type: "CORRELACAO",
    sources: ["DomainConnector (vortex-consulting.org)", "Extração Móvel DEV-2026-001"],
    evidences: ["ev-001", "ev-003"],
    validationStatus: "VALIDADO",
    validatorNotes: "Confirmado cruzamento de contacto telefónico por documentação registral pública e bloco SQLite WAL 4912.",
    createdAt: "2026-10-03 11:45 UTC+1",
    validatedBy: "Capitão Silva (Perito Digital)",
  },
  {
    id: "disc-002",
    searchId: "osint-srch-001",
    investigationId: "CASO-2026-001",
    title: "Endereço IP 185.220.101.45 Identificado como Nó de Saída Tor Activo",
    description: "A resolução DNS do servidor shadow-secure-transfer.net aponta para nó de anonimização Tor listado publicamente, ocultando o tráfego do servidor de comando e controlo.",
    type: "INDICIO",
    sources: ["DNSConnector", "Diretório Público Tor Project"],
    evidences: ["ev-001"],
    validationStatus: "VALIDADO",
    validatorNotes: "Evidência técnica preservada no cofre digital com hash SHA-256.",
    createdAt: "2026-10-02 19:10 UTC+1",
    validatedBy: "Tenente Manuel (Eng. Forense)",
  },
  {
    id: "disc-003",
    searchId: "osint-srch-002",
    investigationId: "CASO-2026-001",
    title: "Procuração Fiduciária Registada em Edital Oficial Vinculada ao NIF do Alvo",
    description: "Publicação oficial mercantil de 2024 comprova mandato outorgado ao Dr. Manuel V. para administração de contas internacionais ligadas à entidade jurídica Vortex Consulting.",
    type: "EVIDENCIA_DOCUMENTADA",
    sources: ["PublicDocumentConnector (Boletim Oficial)"],
    evidences: ["ev-doc-oficial-12"],
    validationStatus: "VALIDADO",
    validatorNotes: "Documento oficial autenticado por perito relator com força probatória plena.",
    createdAt: "2026-10-03 10:00 UTC+1",
    validatedBy: "Capitão Silva (Perito Digital)",
  },
  {
    id: "disc-004",
    searchId: "osint-srch-001",
    investigationId: "CASO-2026-001",
    title: "Variação Sintética de Subdomínios (api.shadow-secure-transfer.net)",
    description: "Identificados certificados de transparência TLS emitidos com múltiplos SANs indicando infraestrutura distribuída para dispersão de chamadas de API.",
    type: "OBSERVACAO",
    sources: ["CertificateConnector (crt.sh)"],
    evidences: ["ev-002"],
    validationStatus: "EM_ANALISE",
    validatorNotes: "Aguardando análise detalhada de conexões ativas no PCAP.",
    createdAt: "2026-10-03 12:00 UTC+1",
  }
];

// Entity Resolution (Correspondência e Desambiguação de Entidades)
export const INITIAL_ENTITY_MATCHES: OsintEntityResolutionMatch[] = [
  {
    id: "match-001",
    primaryEntity: {
      id: "ent-prim-1",
      name: "Dr. Manuel V.",
      type: "PESSOA",
      identifiers: ["NIF: 5410982319", "manuel.v@profundidade.ao"],
      riskScore: 0.85,
      sourcesCount: 4,
      lastObserved: "2026-10-03 09:15 UTC+1",
    },
    matchedEntity: {
      id: "ent-sec-1",
      name: "M. V. Fiduciário (Vortex Consulting)",
      type: "PESSOA",
      identifiers: ["NIF: 5410982319", "Genebra / Luanda"],
      riskScore: 0.90,
      sourcesCount: 3,
      lastObserved: "2024-03-12 00:00 UTC+1",
    },
    confidenceScore: 0.82, // 82%
    indicators: [
      { label: "Mesmo identificador público NIF (5410982319)", verified: true },
      { label: "Vínculo societário com mesmo domínio (vortex-consulting.org)", verified: true },
      { label: "Referência cruzada entre Diário Oficial e Registo Mercantil", verified: true },
      { label: "Compatibilidade de histórico temporal (2024-2026)", verified: true },
    ],
    evidencesCount: 3,
    status: "VALIDADO",
  },
  {
    id: "match-002",
    primaryEntity: {
      id: "ent-prim-2",
      name: "shadow-secure-transfer.net",
      type: "DOMINIO",
      identifiers: ["IP 185.220.101.45", "NS privacy-dns.is"],
      riskScore: 0.95,
      sourcesCount: 3,
      lastObserved: "2026-10-02 18:41 UTC+1",
    },
    matchedEntity: {
      id: "ent-sec-2",
      name: "api.shadow-secure-transfer.net",
      type: "DOMINIO",
      identifiers: ["Certificado TLS crt.sh", "Porta 443"],
      riskScore: 0.88,
      sourcesCount: 2,
      lastObserved: "2026-08-15 14:22 UTC+1",
    },
    confidenceScore: 0.94, // 94%
    indicators: [
      { label: "Mesmo Certificado X.509 em Certificate Transparency", verified: true },
      { label: "Mesmo servidor de nomes autoritativo", verified: true },
      { label: "Alinhamento temporal de emissão criptográfica", verified: true },
    ],
    evidencesCount: 2,
    status: "VALIDADO",
  }
];

// Nós e Arestas do Workspace de Grafo OSINT
export const INITIAL_OSINT_GRAPH_NODES: OsintGraphNode[] = [
  { id: "node-p1", label: "Dr. Manuel V.", type: "PESSOA", riskScore: 0.85, identifier: "NIF 5410982319" },
  { id: "node-e1", label: "Vortex Consulting", type: "EMPRESA", riskScore: 0.70, identifier: "IBC-90219 (Seychelles)" },
  { id: "node-d1", label: "shadow-secure-transfer.net", type: "DOMINIO", riskScore: 0.95, identifier: "A: 185.220.101.45" },
  { id: "node-d2", label: "vortex-consulting.org", type: "DOMINIO", riskScore: 0.75, identifier: "WHOIS Genebra" },
  { id: "node-c1", label: "+41 79 123 4567", type: "TELEFONE_PUBLICO", riskScore: 0.92, identifier: "MSISDN Suíça" },
  { id: "node-ip1", label: "185.220.101.45 (Tor Exit)", type: "IP", riskScore: 0.94, identifier: "AS9009" },
  { id: "node-doc1", label: "Edital Oficial 12/2024", type: "DOCUMENTO", riskScore: 0.30, identifier: "Diário Oficial" },
  { id: "node-crt1", label: "Let's Encrypt Cert SAN", type: "DOCUMENTO", riskScore: 0.60, identifier: "crt.sh #04a981" },
];

export const INITIAL_OSINT_GRAPH_EDGES: OsintGraphEdge[] = [
  {
    id: "edge-o1",
    source: "node-p1",
    target: "node-e1",
    relation: "ASSOCIATED_WITH",
    confidence: 0.98,
    sourceName: "PublicDocumentConnector",
    evidenceRef: "Edital Oficial 12/2024",
    createdAt: "2026-10-03",
    validatedBy: "Capitão Silva",
  },
  {
    id: "edge-o2",
    source: "node-e1",
    target: "node-d2",
    relation: "REGISTERED_TO",
    confidence: 0.95,
    sourceName: "DomainConnector",
    evidenceRef: "RDAP vortex-consulting.org",
    createdAt: "2026-10-03",
    validatedBy: "Capitão Silva",
  },
  {
    id: "edge-o3",
    source: "node-d2",
    target: "node-c1",
    relation: "REFERENCES",
    confidence: 0.96,
    sourceName: "DomainConnector",
    evidenceRef: "RDAP Contact Record",
    createdAt: "2026-10-03",
    validatedBy: "Capitão Silva",
  },
  {
    id: "edge-o4",
    source: "node-d1",
    target: "node-ip1",
    relation: "HOSTED_ON",
    confidence: 0.99,
    sourceName: "DNSConnector",
    evidenceRef: "DNS A Record Query",
    createdAt: "2026-10-02",
    validatedBy: "Tenente Manuel",
  },
  {
    id: "edge-o5",
    source: "node-d1",
    target: "node-crt1",
    relation: "USES",
    confidence: 0.99,
    sourceName: "CertificateConnector",
    evidenceRef: "RFC 6962 CT Log",
    createdAt: "2026-10-02",
    validatedBy: "Tenente Manuel",
  },
  {
    id: "edge-o6",
    source: "node-c1",
    target: "node-p1",
    relation: "SIMILAR_TO",
    confidence: 0.82,
    sourceName: "EntityResolutionEngine",
    evidenceRef: "Crucamento Telefónico UFDR & RDAP",
    createdAt: "2026-10-03",
    validatedBy: "Capitão Silva",
  }
];

// Timeline Automática com Rastreabilidade Criptográfica
export const INITIAL_OSINT_TIMELINE: OsintTimelineEvent[] = [
  {
    id: "time-osint-1",
    date: "12 Março 2024",
    year: 2024,
    month: "Março",
    title: "Constituição Formal da Entidade Societária em Diário Oficial",
    description: "Publicação no Diário da República nomeando Dr. Manuel V. como procurador fiduciário exclusivo.",
    sourceOrigin: "Boletim Oficial de Angola (Edital 12/2024)",
    sourceType: "PublicDocumentConnector",
    contentHash: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
    reliability: "CONFIRMADO",
  },
  {
    id: "time-osint-2",
    date: "14 Março 2024",
    year: 2024,
    month: "Março",
    title: "Registo do Domínio Institucional vortex-consulting.org",
    description: "Domínio registrado com apontamento para servidores DNS corporativos e contacto +41 79 123 4567.",
    sourceOrigin: "ICANN / RDAP Public Record",
    sourceType: "DomainConnector",
    contentHash: "3c2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3210fedcba9876543210fedc",
    reliability: "CONFIRMADO",
  },
  {
    id: "time-osint-3",
    date: "15 Agosto 2026",
    year: 2026,
    month: "Agosto",
    title: "Emissão de Certificado TLS para shadow-secure-transfer.net",
    description: "Certificado X.509 gerado com múltiplos subdomínios (api, vault) registrado em Certificate Transparency.",
    sourceOrigin: "Let's Encrypt / crt.sh CT Log",
    sourceType: "CertificateConnector",
    contentHash: "8e7d6c5b4a3210fedcba9876543210fedcba9876543210fedcba9876543210fe",
    reliability: "CONFIRMADO",
  },
  {
    id: "time-osint-4",
    date: "25 Setembro 2026",
    year: 2026,
    month: "Setembro",
    title: "Alerta Regulatório Público sobre Campanhas de Phishing",
    description: "Entidade reguladora alerta para tentativas de exfiltração envolvendo páginas bancárias clonadas.",
    sourceOrigin: "Boletim de Notícias Financeiras de Angola",
    sourceType: "PublicNewsConnector",
    contentHash: "6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e",
    reliability: "OBSERVADO_PUBLICAMENTE",
  },
  {
    id: "time-osint-5",
    date: "02 Outubro 2026",
    year: 2026,
    month: "Outubro",
    title: "Abertura de Inquérito OSINT & Resolução de Infraestrutura Tor",
    description: "Resolução autoritativa do endereço IP 185.220.101.45 e preservação de evidências sob SHA-256.",
    sourceOrigin: "Motor OSINT PROFUNDIDADE",
    sourceType: "DNSConnector",
    contentHash: "4f9b8c12a3d4e5f67890123456789abcdef0123456789abcdef0123456789abc",
    reliability: "CONFIRMADO",
  }
];

// Jobs de Coletores Assíncronos (Execuções Reais)
export const INITIAL_COLLECTOR_JOBS: OsintCollectorJob[] = [
  {
    id: "job-col-001",
    tenantId: "org-profundidade-lab",
    investigationId: "CASO-2026-001",
    connector: "DomainConnector",
    target: "shadow-secure-transfer.net",
    requestedBy: "Capitão Silva",
    startedAt: "2026-10-02 18:40:02 UTC+1",
    completedAt: "2026-10-02 18:40:45 UTC+1",
    status: "CONCLUIDO",
    resultsCount: 8,
    logSummary: "WHOIS / RDAP resolvido. Registador oculto via WhoisGuard detectado. 2 nameservers identificados.",
  },
  {
    id: "job-col-002",
    tenantId: "org-profundidade-lab",
    investigationId: "CASO-2026-001",
    connector: "CertificateConnector",
    target: "shadow-secure-transfer.net",
    requestedBy: "Capitão Silva",
    startedAt: "2026-10-02 18:41:00 UTC+1",
    completedAt: "2026-10-02 18:41:32 UTC+1",
    status: "CONCLUIDO",
    resultsCount: 3,
    logSummary: "Consulta a 4 logs de Certificate Transparency concluída. 3 subdomínios descobertos via SAN.",
  },
  {
    id: "job-col-003",
    tenantId: "org-profundidade-lab",
    investigationId: "CASO-2026-001",
    connector: "PublicDocumentConnector",
    target: "NIF 5410982319",
    requestedBy: "Tenente Manuel",
    startedAt: "2026-10-03 09:14:10 UTC+1",
    completedAt: "2026-10-03 09:15:30 UTC+1",
    status: "CONCLUIDO",
    resultsCount: 2,
    logSummary: "Varredura textual em 32 diários oficiais de 2024 a 2026 concluída. 1 menção societária identificada.",
  },
  {
    id: "job-col-004",
    tenantId: "org-profundidade-lab",
    investigationId: "CASO-2026-001",
    connector: "SocialPublicConnector",
    target: "@manuel_v_consulting",
    requestedBy: "Tenente Manuel",
    startedAt: "2026-10-03 11:00:00 UTC+1",
    status: "FALHOU",
    resultsCount: 0,
    logSummary: "Fonte não configurada: Token de API de plataforma pública não fornecido nas configurações do Tenant.",
  }
];
